version: '3'
services: 
  api:
    build: 
      dockerfile: packages/server/Dockerfile
      context: ./
    image: agrinessapi:latest
    ports: 
      - "8888:8888"
    environment: 
      NODE_ENV: production
      DB_PATH: mongodb://mongo:27017/agriness-test
      PORT: 8888
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"